version: "3.9"
services:
   app:
      image: vesnam/webapp-pipeline:latest
      container_name: java-web-app-pipeline
      ports:
         - '8081:8080'
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - logvolume03:/var/log
volumes:
   logvolume03: {}
