version: "3.9"
services:
   app:
      image: vesnam/webapp:latest
      container_name: java-web-app
      ports:
         - '8081:8080'
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - logvolume01:/var/log
volumes:
   logvolume01: {}
